version: '3'

services:
    flask_app:
        container_name: flask_app
        restart: always
        build: ./flask_app
        ports:
            - '8000:8000'
        command: >
            bash -c "su - server
            && /usr/src/env/bin/gunicorn -w 2 -k gevent -b 0.0.0.0:8000 -m 007 wsgi:server --timeout 9999"

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - '45045:80'
        depends_on:
            - flask_app
