version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    user: server
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONPATH=/home/server/API_for_Linux
    ports:
      - '8000:8000'
    command: >
      bash -c "
      cd /home/server/API_for_Linux/connector
      && /home/server/.local/bin/gunicorn -w 2 -k gevent -b 0.0.0.0:8000 -m 007 wsgi:server --timeout 9999"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - flask_app
